name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-venv \
              build-essential ccache libncurses6 libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev \
              libpng-dev libfreetype6-dev liblcms2-dev libblas-dev liblapack-dev libatlas-base-dev \
              libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
              libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
              libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
              libmtdev-dev xclip xsel libgl1-mesa-dev libgles2-mesa-dev \
              libopencv-dev libusb-dev libxtst-dev libyaml-dev
          python3 -m pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Initialize Buildozer
        run: |
          buildozer init

      - name: Replace buildozer.spec with custom settings
        run: |
          cat <<EOF > buildozer.spec
          [app]
          title = Motorbike Cleaner
          package.name = motorbikecleaner
          package.domain = org.eladsopher
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,json
          version = 0.1
          requirements = python3,kivy
          orientation = portrait
          osx.python_version = 3.10
          fullscreen = 1
          android.permissions = BLUETOOTH,BLUETOOTH_ADMIN,INTERNET,ACCESS_NETWORK_STATE
          android.api = 31
          android.minapi = 21
          android.ndk = 25bW
          android.archs = armeabi-v7a
          android.debug = 1
          android.build_tools_version = 34.0.0
          android.accept_sdk_license = True
          log_level = 2
          
          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF

      - name: Manually set correct NDK URL
        run: |
          sed -i 's|r25bW-linux.zip|r25b-linux.zip|g' $(grep -rl 'r25bW-linux.zip' .buildozer)

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: motorbike_cleaner_app_apk
          path: bin/*.apk